const CONTACTS_ACTION_TYPES = {
  SET_CONTACTS_MAP: "contacts/SET_CONTACTS_MAP",
  DELETE_CONTACT: "contacts/DELETE_CONTACT",
  EDIT_CONTACT: "contacts/EDIT_CONTACT",
};

export default CONTACTS_ACTION_TYPES;
